// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type DepartmentInput struct {
	Name string `json:"name"`
}

type JobInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Department  int    `json:"department"`
}

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "ADMIN"
	UserRoleManager   UserRole = "MANAGER"
	UserRoleApplicant UserRole = "APPLICANT"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleManager,
	UserRoleApplicant,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleManager, UserRoleApplicant:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
