// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (d *DepartmentQuery) CollectFields(ctx context.Context, satisfies ...string) *DepartmentQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		d = d.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return d
}

func (d *DepartmentQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *DepartmentQuery {
	for _, field := range graphql.CollectFields(ctx, field.Selections, satisfies) {
		switch field.Name {
		case "jobs":
			d = d.WithJobs(func(query *JobQuery) {
				query.collectField(ctx, field)
			})
		}
	}
	return d
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (j *JobQuery) CollectFields(ctx context.Context, satisfies ...string) *JobQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		j = j.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return j
}

func (j *JobQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *JobQuery {
	return j
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (u *UserQuery) CollectFields(ctx context.Context, satisfies ...string) *UserQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		u = u.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return u
}

func (u *UserQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *UserQuery {
	for _, field := range graphql.CollectFields(ctx, field.Selections, satisfies) {
		switch field.Name {
		case "departments":
			u = u.WithDepartments(func(query *DepartmentQuery) {
				query.collectField(ctx, field)
			})
		}
	}
	return u
}
