// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
